# Transition issue to Done
---
- name: Transition issue to Done
  hosts: localhost
  connection: local

  vars:
    server: "{{ lookup('env', 'JIRA_SERVER') }}"
    username: "{{ lookup('hashi_vault', 'secret=cubbyhole/jira:username') | default(lookup('hashi_vault', 'secret=services/data/jira:data')['username'], true) }}"
    password: "{{ lookup('hashi_vault', 'secret=cubbyhole/jira:password') | default(lookup('hashi_vault', 'secret=services/data/jira:data')['password'], true) }}"

  vars_prompt:
    - name: issue
      prompt: Issue key
      private: no

  tasks: 

    - name: Progress
      jira:
        uri: "{{ server }}"
        username: "{{ username }}"
        password: "{{ password }}"
        issue: "{{ issue }}"
        operation: transition
        status: Start Progress
      tags:
        - progress

    - name: Review
      jira:
        uri: "{{ server }}"
        username: "{{ username }}"
        password: "{{ password }}"
        issue: "{{ issue }}"
        operation: transition
        status: In Review
      tags:
        - done

    - name: Ready for QA
      jira:
        uri: "{{ server }}"
        username: "{{ username }}"
        password: "{{ password }}"
        issue: "{{ issue }}"
        operation: transition
        status: Ready for QA
      tags:
        - done

    - name: Done
      jira:
        uri: "{{ server }}"
        username: "{{ username }}"
        password: "{{ password }}"
        issue: "{{ issue }}"
        operation: transition
        status: Done
      tags:
        - done
