# Transition issue to Done
---
- name: Transition issue to Done
  hosts: localhost
  connection: local
  ignore_errors: yes

  vars:
    server: "{{ lookup('env', 'JIRA_SERVER') }}"
    username: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=cubbyhole/jira:username') | default(lookup('community.hashi_vault.hashi_vault', 'secret=services/data/jira:data')['username'], true) }}"
    password: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=cubbyhole/jira:password') | default(lookup('community.hashi_vault.hashi_vault', 'secret=services/data/jira:data')['password'], true) }}"

  vars_prompt:
    - name: issue
      prompt: Issue key
      private: no

  tasks: 

    - name: env
      debug: msg="{{ username }}"

    - name: Progress
      jira:
        uri: "{{ server }}"
        username: "{{ username }}"
        password: "{{ password }}"
        issue: "{{ issue }}"
        operation: transition
        status: "{{ item }}"
      tags:
        - progress
        - none
      loop:
        - Start Progress
        - In Analysis
        - Request Estimate
        - To approve
        - Development 
        - In Development 

    - name: Review
      jira:
        uri: "{{ server }}"
        username: "{{ username }}"
        password: "{{ password }}"
        issue: "{{ issue }}"
        operation: transition
        status: "{{ item }}"
      tags:
        - review
        - none
      loop:
        - Review
        - Review -1
        - In Review
        - Ready for QA 

    - name: Done
      jira:
        uri: "{{ server }}"
        username: "{{ username }}"
        password: "{{ password }}"
        issue: "{{ issue }}"
        operation: transition
        status: "{{ item }}"
      tags:
        - done
        - none
      loop:
        - Review Done 
        - Resolved 
        - Done 

    - name: Close
      jira:
        uri: "{{ server }}"
        username: "{{ username }}"
        password: "{{ password }}"
        issue: "{{ issue }}"
        operation: transition
        status: "{{ item }}"
      tags:
        - close
        - none
      loop:
        - Reject
        - Close 
